#!/bin/bash

find . \
\( \
 -path './out' -o \
 -path './build' -o \
 -path './Source/ThirdParty' \
\) -prune \
-o -name '*.[ch]' \
-o -name '*.cc' \
-o -name '*.cpp' \
-o -name '*.hpp' \
-o -name '*.java' \
> ./cscope.files

# -b: just build
# -q: create inverted index
# -k: kernel mode
cscope -Rbqk

#ctags -R --tag-relative=yes
ctags -L ./cscope.files

