#!/bin/bash

find ./ -type f -path './out/*' -prune -o -path './third_party/*' -prune \
-o -name '*.[ch]' \
-o -name '*.cc' \
-o -name '*.cpp' \
-o -name '*.hpp' \
-o -name '*.java' \
> ./cscope.files

# -b: just build
# -q: create inverted index
# -k: kernel mode
cscope -Rbqk

#ctags -R --tag-relative=yes
ctags -L ./cscope.files

rm -rf ./cscope.files
